// localStorage.clear()

const employees = [
  {
    id: 1,
    firstName: "Ali",
    email: "e@e.com",
    password: "1234",
    taskCounters: { active: 2, newTask: 5, completed: 2, failed: 1 },
    tasks: [
      {
        taskNumber: 2,
        title: "Prepare Sales Report",
        description: "Create monthly sales report for management",
        date: "2026-01-05",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Client Follow-up",
        description: "Follow up with pending clients via email",
        date: "2026-01-03",
        category: "Communication",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Data Cleanup",
        description: "Clean old entries from the database",
        date: "2026-01-02",
        category: "Database",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskNumber: 2,
        title: "Team Meeting",
        description: "Weekly sync with team members",
        date: "2026-01-06",
        category: "Meeting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Client Presentation",
        description: "Present new project proposal to client",
        date: "2026-01-07",
        category: "Presentation",
        active: false,
        newTask: false,
        completed: 1,
        failed: 0,
      },
    ],
  },
  {
    id: 2,
    firstName: "Ahmed",
    email: "employee2@example.com",
    password: "1234",
    taskCounters: { active: 3, newTask: 1, completed: 1, failed: 0 },
    tasks: [
      {
        taskNumber: 2,
        title: "UI Fixes",
        description: "Fix alignment issues on dashboard",
        date: "2026-01-06",
        category: "Frontend",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Bug Testing",
        description: "Test reported bugs from QA team",
        date: "2026-01-04",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Deploy Build",
        description: "Deploy latest build to staging server",
        date: "2026-01-01",
        category: "Deployment",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Code Review",
        description: "Review team members code",
        date: "2026-01-07",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Write Unit Tests",
        description: "Add unit tests for new features",
        date: "2026-01-08",
        category: "Testing",
        active: false,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    firstName: "Usman",
    email: "employee3@example.com",
    password: "1234",
    taskCounters: { active: 2, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        taskNumber: 2,
        title: "Write API Docs",
        description: "Document authentication APIs",
        date: "2026-01-07",
        category: "Documentation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Optimize Queries",
        description: "Improve slow SQL queries",
        date: "2026-01-03",
        category: "Backend",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Server Monitoring",
        description: "Monitor server performance",
        date: "2026-01-02",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskNumber: 2,
        title: "Implement Cache",
        description: "Add caching for API responses",
        date: "2026-01-06",
        category: "Backend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Database Backup",
        description: "Backup all databases",
        date: "2026-01-08",
        category: "Database",
        active: false,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    firstName: "Bilal",
    email: "employee4@example.com",
    password: "1234",
    taskCounters: { active: 2, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        taskNumber: 2,
        title: "Design Banner",
        description: "Create banner for marketing campaign",
        date: "2026-01-06",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Update Brand Kit",
        description: "Update company brand assets",
        date: "2026-01-04",
        category: "Design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Export Assets",
        description: "Export assets in required formats",
        date: "2026-01-02",
        category: "Assets",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskNumber: 2,
        title: "Social Media Post",
        description: "Create content for social media",
        date: "2026-01-07",
        category: "Marketing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Email Campaign",
        description: "Design and send email campaign",
        date: "2026-01-08",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstName: "Hassan",
    email: "employee5@example.com",
    password: "1234",
    taskCounters: { active: 3, newTask: 1, completed: 1, failed: 0 },
    tasks: [
      {
        taskNumber: 2,
        title: "Content Writing",
        description: "Write blog post for website",
        date: "2026-01-08",
        category: "Content",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "SEO Optimization",
        description: "Optimize blog for SEO",
        date: "2026-01-05",
        category: "Marketing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Publish Post",
        description: "Publish approved blog post",
        date: "2026-01-01",
        category: "Publishing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Update Website",
        description: "Add new pages to website",
        date: "2026-01-06",
        category: "Web",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        title: "Marketing Report",
        description: "Prepare monthly marketing report",
        date: "2026-01-07",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 101,
    email: "admin@example.com",
    password: "1234",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
